export default [
  {
    id: 1,
    title: `Wood and stone place 1`,
    price: 80,
    previewImage: `img/room.jpg`,
    images: [`img/room.jpg`, `img/apartment-01.jpg`, `img/apartment-02.jpg`, `img/apartment-03.jpg`, `img/studio-01.jpg`, `img/apartment-01.jpg`],
    description: `A quiet cozy and picturesque that hides behind a a river by the unique lightness of Amsterdam.`,
    rating: 4,
    isPremium: false,
    type: `room`,
    bedrooms: 1,
    maxAdults: 2,
    goods: [`Wi-Fi`, `Washing machine`, `Heating`, `Kitchen`],
    host: {
      name: `Angelina`,
      super: true,
      avatarUrl: `img/avatar-angelina.jpg`,
    },
    city: {
      name: `Amsterdam`,
      coords: [52.377956, 4.897070],
    },
    coords: [52.369553943508, 4.85309666406198],
  },
  {
    id: 1,
    title: `Wood and stone place 11`,
    price: 80,
    previewImage: `img/room.jpg`,
    images: [`img/room.jpg`, `img/apartment-01.jpg`, `img/apartment-02.jpg`, `img/apartment-03.jpg`, `img/studio-01.jpg`, `img/apartment-01.jpg`],
    description: `A quiet cozy and picturesque that hides behind a a river by the unique lightness of Amsterdam.`,
    rating: 4,
    isPremium: false,
    type: `room`,
    bedrooms: 1,
    maxAdults: 2,
    goods: [`Wi-Fi`, `Washing machine`, `Heating`, `Kitchen`],
    host: {
      name: `Angelina`,
      super: true,
      avatarUrl: `img/avatar-angelina.jpg`,
    },
    city: {
      name: `Amsterdam`,
      coords: [52.377956, 4.897070],
    },
    coords: [52.3909553943508, 4.929309666406198],
  },
  {
    id: 1,
    title: `Wood and stone place 111`,
    price: 80,
    previewImage: `img/room.jpg`,
    images: [`img/room.jpg`, `img/apartment-01.jpg`, `img/apartment-02.jpg`, `img/apartment-03.jpg`, `img/studio-01.jpg`, `img/apartment-01.jpg`],
    description: `A quiet cozy and picturesque that hides behind a a river by the unique lightness of Amsterdam.`,
    rating: 4,
    isPremium: false,
    type: `room`,
    bedrooms: 1,
    maxAdults: 2,
    goods: [`Wi-Fi`, `Washing machine`, `Heating`, `Kitchen`],
    host: {
      name: `Angelina`,
      super: true,
      avatarUrl: `img/avatar-angelina.jpg`,
    },
    city: {
      name: `Amsterdam`,
      coords: [52.377956, 4.897070],
    },
    coords: [52.3809553943508, 4.939309666406198],
  },
  {
    id: 2,
    title: `Wood and stone place 2`,
    price: 80,
    previewImage: `img/room.jpg`,
    images: [`img/room.jpg`, `img/apartment-01.jpg`, `img/apartment-02.jpg`, `img/apartment-03.jpg`, `img/studio-01.jpg`, `img/apartment-01.jpg`],
    description: `A quiet cozy and picturesque that hides behind a a river by the unique lightness of Amsterdam.`,
    rating: 4,
    isPremium: false,
    type: `room`,
    bedrooms: 1,
    maxAdults: 2,
    goods: [`Wi-Fi`, `Washing machine`, `Heating`, `Kitchen`],
    host: {
      name: `Angelina`,
      super: true,
      avatarUrl: `img/avatar-angelina.jpg`,
    },
    city: {
      name: `Amsterdam`,
      coords: [52.377956, 4.897070],
    },
    coords: [52.3909553943508, 4.85309666406198],
  },
  {
    id: 2,
    title: `Wood and stone place 22`,
    price: 80,
    previewImage: `img/room.jpg`,
    images: [`img/room.jpg`, `img/apartment-01.jpg`, `img/apartment-02.jpg`, `img/apartment-03.jpg`, `img/studio-01.jpg`, `img/apartment-01.jpg`],
    description: `A quiet cozy and picturesque that hides behind a a river by the unique lightness of Amsterdam.`,
    rating: 4,
    isPremium: false,
    type: `room`,
    bedrooms: 1,
    maxAdults: 2,
    goods: [`Wi-Fi`, `Washing machine`, `Heating`, `Kitchen`],
    host: {
      name: `Angelina`,
      super: true,
      avatarUrl: `img/avatar-angelina.jpg`,
    },
    city: {
      name: `Amsterdam`,
      coords: [52.377956, 4.897070],
    },
    coords: [52.3909553943508, 4.929309666406198],
  },
  {
    id: 2,
    title: `Wood and stone place 222`,
    price: 80,
    previewImage: `img/room.jpg`,
    images: [`img/room.jpg`, `img/apartment-01.jpg`, `img/apartment-02.jpg`, `img/apartment-03.jpg`, `img/studio-01.jpg`, `img/apartment-01.jpg`],
    description: `A quiet cozy and picturesque that hides behind a a river by the unique lightness of Amsterdam.`,
    rating: 4,
    isPremium: false,
    type: `room`,
    bedrooms: 1,
    maxAdults: 2,
    goods: [`Wi-Fi`, `Washing machine`, `Heating`, `Kitchen`],
    host: {
      name: `Angelina`,
      super: true,
      avatarUrl: `img/avatar-angelina.jpg`,
    },
    city: {
      name: `Amsterdam`,
      coords: [52.377956, 4.897070],
    },
    coords: [52.3809553943508, 4.939309666406198],
  },
  {
    id: 3,
    title: `Wood and stone place 3`,
    price: 80,
    previewImage: `img/room.jpg`,
    images: [`img/room.jpg`, `img/apartment-01.jpg`, `img/apartment-02.jpg`, `img/apartment-03.jpg`, `img/studio-01.jpg`, `img/apartment-01.jpg`],
    description: `A quiet cozy and picturesque that hides behind a a river by the unique lightness of Amsterdam.`,
    rating: 4,
    isPremium: false,
    type: `room`,
    bedrooms: 1,
    maxAdults: 2,
    goods: [`Wi-Fi`, `Washing machine`, `Heating`, `Kitchen`],
    host: {
      name: `Angelina`,
      super: true,
      avatarUrl: `img/avatar-angelina.jpg`,
    },
    city: {
      name: `Amsterdam`,
      coords: [52.377956, 4.897070],
    },
    coords: [52.3809553943508, 4.939309666406198],
  },
  {
    id: 3,
    title: `Wood and stone place 33`,
    price: 80,
    previewImage: `img/room.jpg`,
    images: [`img/room.jpg`, `img/apartment-01.jpg`, `img/apartment-02.jpg`, `img/apartment-03.jpg`, `img/studio-01.jpg`, `img/apartment-01.jpg`],
    description: `A quiet cozy and picturesque that hides behind a a river by the unique lightness of Amsterdam.`,
    rating: 4,
    isPremium: false,
    type: `room`,
    bedrooms: 1,
    maxAdults: 2,
    goods: [`Wi-Fi`, `Washing machine`, `Heating`, `Kitchen`],
    host: {
      name: `Angelina`,
      super: true,
      avatarUrl: `img/avatar-angelina.jpg`,
    },
    city: {
      name: `Amsterdam`,
      coords: [52.377956, 4.897070],
    },
    coords: [52.369553943508, 4.85309666406198],
  },
  {
    id: 3,
    title: `Wood and stone place 333`,
    price: 80,
    previewImage: `img/room.jpg`,
    images: [`img/room.jpg`, `img/apartment-01.jpg`, `img/apartment-02.jpg`, `img/apartment-03.jpg`, `img/studio-01.jpg`, `img/apartment-01.jpg`],
    description: `A quiet cozy and picturesque that hides behind a a river by the unique lightness of Amsterdam.`,
    rating: 4,
    isPremium: false,
    type: `room`,
    bedrooms: 1,
    maxAdults: 2,
    goods: [`Wi-Fi`, `Washing machine`, `Heating`, `Kitchen`],
    host: {
      name: `Angelina`,
      super: true,
      avatarUrl: `img/avatar-angelina.jpg`,
    },
    city: {
      name: `Amsterdam`,
      coords: [52.377956, 4.897070],
    },
    coords: [52.3909553943508, 4.85309666406198],
  },
  {
    id: 4,
    title: `Wood and stone place 4`,
    price: 80,
    previewImage: `img/room.jpg`,
    images: [`img/room.jpg`, `img/apartment-01.jpg`, `img/apartment-02.jpg`, `img/apartment-03.jpg`, `img/studio-01.jpg`, `img/apartment-01.jpg`],
    description: `A quiet cozy and picturesque that hides behind a a river by the unique lightness of Amsterdam.`,
    rating: 4,
    isPremium: false,
    type: `room`,
    bedrooms: 1,
    maxAdults: 2,
    goods: [`Wi-Fi`, `Washing machine`, `Heating`, `Kitchen`],
    host: {
      name: `Angelina`,
      super: true,
      avatarUrl: `img/avatar-angelina.jpg`,
    },
    city: {
      name: `Amsterdam`,
      coords: [52.377956, 4.897070],
    },
    coords: [52.3909553943508, 4.929309666406198],
  },
  {
    id: 4,
    title: `Wood and stone place 44`,
    price: 80,
    previewImage: `img/room.jpg`,
    images: [`img/room.jpg`, `img/apartment-01.jpg`, `img/apartment-02.jpg`, `img/apartment-03.jpg`, `img/studio-01.jpg`, `img/apartment-01.jpg`],
    description: `A quiet cozy and picturesque that hides behind a a river by the unique lightness of Amsterdam.`,
    rating: 4,
    isPremium: false,
    type: `room`,
    bedrooms: 1,
    maxAdults: 2,
    goods: [`Wi-Fi`, `Washing machine`, `Heating`, `Kitchen`],
    host: {
      name: `Angelina`,
      super: true,
      avatarUrl: `img/avatar-angelina.jpg`,
    },
    city: {
      name: `Amsterdam`,
      coords: [52.377956, 4.897070],
    },
    coords: [52.369553943508, 4.85309666406198],
  },
  {
    id: 4,
    title: `Wood and stone place 444`,
    price: 80,
    previewImage: `img/room.jpg`,
    images: [`img/room.jpg`, `img/apartment-01.jpg`, `img/apartment-02.jpg`, `img/apartment-03.jpg`, `img/studio-01.jpg`, `img/apartment-01.jpg`],
    description: `A quiet cozy and picturesque that hides behind a a river by the unique lightness of Amsterdam.`,
    rating: 4,
    isPremium: false,
    type: `room`,
    bedrooms: 1,
    maxAdults: 2,
    goods: [`Wi-Fi`, `Washing machine`, `Heating`, `Kitchen`],
    host: {
      name: `Angelina`,
      super: true,
      avatarUrl: `img/avatar-angelina.jpg`,
    },
    city: {
      name: `Amsterdam`,
      coords: [52.377956, 4.897070],
    },
    coords: [52.3909553943508, 4.85309666406198],
  },
];
